version: '3'
services:
   app: 
      container_name: ffxiv-organizer-users-api
      restart: always
      build: .
      image: ffxiv-organizer-users-api
      ports:
         - "9876:9876"
      networks:
         - ffxiv-organizer-network
networks:
   ffxiv-organizer-network:
      external: true