version: '3'
services:
   app:
      container_name: ffxiv-organizer-inventories-db
      restart: always
      build: .
      image: ffxiv-organizer-inventories-db
      command: mongod --port 33333
      ports:
         - "127.0.0.1:33333:33333"
      volumes:
         - ./data/db:/data/db
      networks:
         - ffxiv-organizer-network
networks:
  ffxiv-organizer-network:
      external: true
